1.1.0
ktsstudio/mediaproject-stores pull request #1
Opened 2021-12-29 11:34 UTC by andrewgul

2022-01-17 15:02 UTC, n-merkulova requested changes

2022-01-17 15:02 UTC, n-merkulova commented on src/stores/BaseSubstore.ts
> +      setError: action,
сюда еще sendSentryError наверное надо?

2022-01-17 15:02 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +  setUserData = (value: null | UserT) => {
мб просто setUser?

2022-01-17 15:02 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +    // @ts-ignore
а почему тут тс игнор?

2022-01-17 15:02 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +    this.setUserData(response.user as UserT); // почему-то ругается
видимо потому что user в AuthT у нас может быть не UserT. вообще точно нужен отдельный тип для ответа на запрос авторизации? мб в ответе просто делать `ApiResponse<{ user: UserT }>`?

2022-01-17 15:02 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +      this.sendSentryError(error, { errorData, url });
выглядит, будто бы url лишняя переменная

2022-01-17 15:02 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +      this.sendSentryError(error, { errorData, url, name, value });
здесь тоже будто бы url лишняя переменная

2022-01-17 15:03 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +  flag = async (name: string, value: boolean | number): Promise<boolean> => {
тут в value по дефолту все же только boolean у бэкендеров

2022-01-17 15:13 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +  flag = async (name: string, value: boolean | number): Promise<boolean> => {
кстати я подумала, что мб имело бы смысл хранить объект с флагами в сторе

2022-01-17 15:14 UTC, n-merkulova commented on src/stores/BaseUserStore.ts
> +
можно добавить сюда еще поле messagesAllowed, оно вроде тоже есть в шаблоне у бэкендеров. нужно уточнить у кого-нибудь из них

2022-01-17 15:26 UTC, natalya-z commented on src/index.ts
> +import BaseUserStore from './stores/BaseUserStore';
надо претиер прогнать, чтобы было везде одинаковые кавычки

2022-01-17 15:29 UTC, natalya-z commented on src/stores/BaseUserStore.ts
> +    const { response, error, errorData }: ApiResponse<AuthT> = await api(`${url}${window.search!}`, method);
почем после window.search восклицательный знак?

2022-01-17 15:45 UTC, natalya-z requested changes

2022-01-17 15:45 UTC, natalya-z commented on src/stores/BaseUserStore.ts
> +    const { response, error, errorData }: ApiResponse<AuthT> = await api(`${url}${window.search!}`, method);
почему после window.search восклицательный знак?

2022-01-17 15:45 UTC, natalya-z commented on src/stores/BaseSubstore.ts
> +  sendSentryError = (exception: any, params: Record<string, unknown>): void => {
у exception нет типа в сентри?

2022-01-17 15:45 UTC, natalya-z commented on src/stores/BaseSubstore.ts
> +      Sentry.captureException(exception, params);
может добавить проверку на то, что это прод?

2022-01-17 15:45 UTC, natalya-z commented on src/stores/types/api.ts
> +export type ApiSexType = 0 | 1 | 2;
было бы здорово подписать кто - что значит, чтобы не бегать в док

2022-01-17 15:45 UTC, natalya-z commented on src/stores/types/api.ts
> +  flags?: Record<string, boolean>;
Здесь в типах надо добавить  `boolean | number` для согласования с типами в функции отправки флагов

2022-01-17 15:45 UTC, natalya-z commented on src/stores/types/api.ts
> +  updated_dt: string;
created_dt: string;
updated_dt: string;

не встречала, чтобы эти поля использовали, нужно ли их вообще отмечать тут?

насчет added_from не уверена для чего он, стоит спросить бэкендеров или подписать что это

2022-01-17 15:45 UTC, natalya-z commented on src/stores/BaseUserStore.ts
> +    const { response, error, errorData } = await api(...this.rootStore._urls.flag, { name, value });
может так случиться, что в ответ придет `data: {} `и `response` будет `undefined`, в таком случае лучше ориентироваться на `error`

2022-01-19 03:46 UTC, AliceSitedge requested changes

2022-01-19 03:46 UTC, AliceSitedge commented on src/stores/BaseUserStore.ts
> +    const { response, error, errorData }: ApiResponse<AuthT> = await api(`${url}${window.search!}`, method);
В новой версии mediaproject-utils метод api принимает объект типа `{ url: string; method: Method }`, наверное лучше один тип везде использовать для урлов, либо массивом, либо объектом

2022-01-19 03:46 UTC, AliceSitedge commented on src/stores/BaseUserStore.ts
> +      const [url] = this.rootStore._urls.getUser;
Поле `this.rootStore._urls.getUser` можно повыше достать, оно тут два раза получается

2022-01-19 03:46 UTC, AliceSitedge commented on src/stores/BaseSubstore.ts
> +      Sentry.captureException(exception, params);
Тут нужно либо добавить флаг на то, нужно ли отправлять ошибки в сентри, чтобы включить его перед запуском в прод, либо проверить, что если не будет вызван Sentry.init, то тут не будет никаких ошибок и лишних запросов. Ну и да, проверку на прод нужно

2022-01-19 03:46 UTC, AliceSitedge commented on src/stores/BaseSubstore.ts
> +    this.setError(true);
А для чего предполагается использовать поле `error`? Получается, оно будет `true` с того момента, как я отправлю первую ошибку в сентри? Может здесь не нужно вызывать этот метод, а вызывать его по надобности, например, в методе `auth` это наверное нужно, потому что мы скорее всего не захотим пропускать юзера дальше, если произошла ошибка, а если у нас не получилось отправить какой-то флаг, кажется, что это не так критично

2022-02-16 15:30 UTC, andrewgul commented on src/stores/BaseUserStore.ts
> +    const { response, error, errorData }: ApiResponse<AuthT> = await api(`${url}${window.search!}`, method);
TS ругался, надо было добавить `interface Window` в `typings.d.ts` и ругаться перестали

2022-02-16 15:50 UTC, andrewgul commented on src/stores/BaseSubstore.ts
> +  sendSentryError = (exception: any, params: Record<string, unknown>): void => {
неа(
<img width="818" alt="Снимок экрана 2022-02-16 в 17 11 12" src="https://user-images.githubusercontent.com/56839604/154302290-2cd37189-a5f4-460b-b5cc-428c6fc59e26.png">

2022-03-02 12:57 UTC, merged