Добавление FieldModel и ListModel
ktsstudio/mediaproject-stores pull request #10
Opened 2023-11-21 11:10 UTC by Christik

Задача:
- [SPECIAL-13089](https://youtrack.kts.studio/issue/SPECIAL-13089) [mediaproject-stores] Добавить новые модели

Добавлены модели:
- `FieldModel` для работы с изменяемыми полями ([пример](https://gitlab.team.ktsstudio.ru/n-plus-one/animal-lives-front/-/blob/main/src/store/models/FieldModel/FieldModel.ts)).
- `ListModel` для работы со списками однотипных элементов ([пример](https://gitlab.team.ktsstudio.ru/n-plus-one/restoration-of-history-front/-/blob/main/src/store/models/ListModel/ListModel.ts)).

В `ListModel` добавлен метод `_normalize()`, чтобы приводить исходный список к объекту внутри модели, а не снаружи.

2023-11-21 14:34 UTC, dewolixgit commented on src/models/FieldModel/FieldModel.ts
> +  }
В порядке бреда вкидываю идею здесь возвращать из метода то же значение, которое мы в него кладём:
```suggestion
  changeValue<I extends T>(value: I): I {
    this._value = value;
  }
```

Тогда откроются некоторые фунционально прикольные штуки:
1. Можно будет делать цепочки вызовов, например с той же `string`:
```typescript
field.changeValue(' sOmE tExT ').trim().toLowerCase()
```
2. Можно будет удобнее пользоваться интересными операторами (функциями) из функционального программирования, по типу [pipe](https://dev.to/ecyrbe/how-to-use-advanced-typescript-to-define-a-pipe-function-381h):
```typescript
pipe(
  -20.5,
  field.changeValue,
  Math.abs,
  Math.trunc,
  toSmth
)
```

И другие более узкие вещи типа совмещения операций изменения значения и возвращения из некоторого метода этого же значения:
```typescript
// Если бы T в FieldModel<T> был типа string | null, то компилятор бы ругнулся.
// Если нужно вернуть именно void, то можно написать `return void field.changeValue('bla bla')`
someMethod(): string {
  return field.changeValue('bla bla');
}
```
, вместо вот такого:
```typescript
// С учётом, что T в FieldModel<T> типа string | null
someMethod(): string {
  const value = 'bla bla'
  field.changeValue(value);
  return value;
}
```

Но в целом прям узкие кейсы и возможно притянуто. Лучше услышать мнение других фронтов

2023-11-21 14:46 UTC, dewolixgit commented on src/models/FieldModel/FieldModel.ts
> +  constructor(value: T) {
Быть может, стоит ввести второй необязательный аргумент с объектом-конфигом, где бы можно было указать значение по умолчанию, отличное от передаваемого первым аргументом value. Если в конфиге значение по умолчанию не указано, оно бы было равно значению первого аргумента value. В целом можно и не объект-конфиг, а просто второй необязательный аргумент, но мало ли чего в будущем захочется добавить в эту модель.

Просто иногда хочется и инициализировать модель осмысленным значением и предусмотреть значение для сброса. Например, если у нас может быть некоторое поле, пользовательский ввод в которое мы запоминаем в базе и воспроизводим при повторном входе. Так вот инциализирующим значением для нас будет вот это значение, которое мы запомнили в базе. Однако нам бы хотелось оставить возможность сбросить это поле, сделав пустым (хотя да, можно бы было и "вручную" через changeValue изменить, но через reset красивее)

Возможно пример не очень удачный и коммент тоже притянут за уши, поэтому здесь тоже можно послушать мнение других разработчиков

2023-11-22 08:32 UTC, AliceSitedge requested changes

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/FieldModel/FieldModel.ts
> +  private _initialValue: T;
Можно сделать readonly

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/ListModel.ts
> +  private _getKeyForItem: (item: T) => K;
readonly

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/ListModel.ts
> +  private _normalize(items: T[], getKeyForItem: (item: T) => K) {
А getKeyForItem же можно взять из уже сохраненного поля?

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/ListModel.ts
> +  getEntityByKey = (key: K): T => {
По-хорошему тут может быть и undefined

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/ListModel.ts
> +      this._keys.unshift(...keys);
А тут нет проверки на то, были ли уже в массиве ключей такие ключи. Может для добавления каждой сущности использовать метод addEntity?

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/ListModel.ts
> +      reset: action,
Может все экшены сделать action.bound?

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/types.ts
> +export interface IList<T, K extends string | number | symbol = string> {
В самом классе вроде symbol не учитывается, лучше привести к одному виду наверное

2023-11-22 08:32 UTC, AliceSitedge commented on src/models/lists/ListModel/types.ts
> +  getEntityByIndex(index: number): T;
Здесь тоже | null по идее

2023-11-22 08:33 UTC, AliceSitedge commented on CHANGELOG.md
> +## v2.3.0
Также я бы предложила в этой задаче заодно поправить [этот ишью](https://github.com/ktsstudio/mediaproject-stores/issues/9)

2023-11-22 08:41 UTC, AliceSitedge commented on src/models/FieldModel/FieldModel.ts
> +  constructor(value: T) {
Согласна, что может понадобиться такой кейс. Главное чтобы можно было спокойно использовать эту модель без необходимости прокидывать всегда два аргумента, если этот кейс не нужен

2023-11-22 08:42 UTC, AliceSitedge commented on src/models/FieldModel/FieldModel.ts
> +  }
Да кажется можно, ничего не сломается от этого

2023-11-29 09:22 UTC, AliceSitedge requested changes

2023-11-29 09:22 UTC, AliceSitedge commented on src/models/FieldModel/FieldModel.ts
> +    this._initialValue = config?.initialValue ?? value;
А если был передан конфиг `{ initialValue: null }`, то получается это значение не будет учитываться, потому что оператор `??` пропускает null и undefined
Думаю нужно либо явно проверять на undefined, либо сделать значение по умолчанию в аргументе

2023-11-29 09:22 UTC, AliceSitedge commented on src/models/FieldModel/FieldModel.ts
> +  changeValue<I extends T>(value: I): I {
Не поняла, зачем второй дженерик, не получилось бы просто `changeValue(value: T): T`?

2023-12-07 10:49 UTC, dewolixgit commented on src/models/FieldModel/FieldModel.ts
> +  changeValue<I extends T>(value: I): I {
> Не поняла, зачем второй дженерик, не получилось бы просто `changeValue(value: T): T`?

Продолжая пример с какой-нибудь, например, строкой, то T может быть `string | null`. Тогда ts ругнётся на цепочку `field.changeValue().trim()`, потому что результат метода может быть `null`. А второй дженерик явно даёт понять: в результате `changeValue` вернёт именно но, что передали в аргумент, а не обобщённое множество типов T

2023-12-29 08:38 UTC, AliceSitedge commented on src/models/FieldModel/FieldModel.ts
> +  changeValue<I extends T>(value: I): I {
Шок

2023-12-29 08:39 UTC, AliceSitedge approved these changes

2023-12-29 12:27 UTC, merged