v2.3.0: Создание стора с базовыми параметрами приложения
ktsstudio/mediaproject-stores pull request #11
Opened 2023-12-18 17:16 UTC by kurakinasv

**Задача [SPECIAL-13849](https://youtrack.kts.studio/issue/SPECIAL-13849/mediaproject-stores-Sdelat-stor-s-bazovymi-parametrami-prilozheniya):**

- создать стор с параметрами для использования вместо утилиты `initializeAppParams` 

**Что было сделано:**

- Опираясь на [пример в другом проекте](https://git.kts.tech/mailru-nonstandart/sber-chan-comics-front/-/blob/main/src/store/globals/appParams/AppParamsStore/AppParamsStore.ts) был создан стор `AppParamsStore` для инициализации и хранения базовых параметров приложения. Ранее они инициализировались с помощью `initializeAppParams` и хранились в `window`
- Обращения к `window` за этими параметрами были заменены на обращение к инстансу этого стора

**Как тестировалось:**

- mediaproject-stores была связана с mediaproject-utils. Версия utils для линковки взята из [этого PR](https://github.com/ktsstudio/mediaproject-utils/pull/16)
- К проекту с помощью `yarn link` были подключены mediaproject-stores и mediaproject-utils
- Закомменчена часть с авторизацией в проекте
- В проекте заменено использование локальной функции `checkDev` на одноименную функцию из utils + заменен стор `AppParamsStore` на одноименный из mediaproject-stores
- Окружение определялось правильно

**Проблемы:**

- Для проверки изменений пришлось понизить версию реакта и типов в проекте до 18, так как возникала ошибка с `ErrorBoundary`
- Также пришлось закомментить часть кода, использующую `CSSTransition`, так как возникала та же ошибка
- Использование одинаковых версий реакта и типов и в либах, и в проекте не помогло

2023-12-25 08:43 UTC, AliceSitedge requested changes

2023-12-25 08:43 UTC, AliceSitedge commented on src/stores/AppParamsStore/AppParamsStore.ts
> +    this.isDev = checkDev(this.isProd); // @ktsstudio/mediaproject-utils >= 5.0.0
Это решается тем, что в peerDependencies указывается версия ^5.0.0. Но поскольку она еще не опубликована, то я это буду делать при публикации, а комментарий можно убрать

2023-12-25 08:43 UTC, AliceSitedge commented on src/stores/AppParamsStore/AppParamsStore.ts
> +export const appParamsStore = new AppParamsStore();
Я думаю библиотека должна экспортировать только класс, а инстанс стора должен создаваться внутри проекта. Иначе как от него наследоваться

2023-12-25 08:43 UTC, AliceSitedge commented on src/stores/SentryStore/utils.ts
> +      (appParamsStore.isProd
А если в других утилитах используются эти параметры, то нужно передавать их через аргументы теперь

2023-12-29 07:51 UTC, AliceSitedge approved these changes

2023-12-29 07:54 UTC, AliceSitedge commented on CHANGELOG.md
> +## v2.3.0
Видимо 3.0.0, потому что где-то добавлены новые аргументы функциям

2023-12-29 07:56 UTC, AliceSitedge commented on CHANGELOG.md
> +- [-] обращение к `window` за базовыми параметрами
```suggestion
- [-] удалено обращение к `window` за базовыми параметрами
```

2024-02-05 08:53 UTC, closed without merging

2024-02-05 08:54 UTC, Christik commented
Все изменения из этого ПРа перенесены в #12