feat: updated FieldModel
ktsstudio/mediaproject-stores pull request #14
Opened 2024-06-20 09:32 UTC by BobbyLilD

## Что сделано
- Обновлена FieldModel

2024-06-24 07:26 UTC, Margot07008 commented on CHANGELOG.md
> +- [*] Произведен ряд изменений в FieldModel
каких?))

2024-06-24 07:26 UTC, Margot07008 commented on src/models/FieldModel/FieldModel.ts
> +  _resetTouched = (): void => {
private

2024-06-24 07:26 UTC, Margot07008 commented on src/models/FieldModel/FieldModel.ts
> +  protected _initialValue: T;
по идее readonly поле

2024-06-24 08:14 UTC, n-merkulova requested changes

2024-06-24 08:14 UTC, n-merkulova commented on src/models/FieldModel/FieldModel.ts
> +type PrivateFields =
[+] я бы предложила поля сделать protected для удобства. чтоб можно было переопределять логику в наследнике

2024-06-24 08:14 UTC, n-merkulova commented on src/models/FieldModel/FieldModel.ts
> -  private readonly _initialValue: T;
[!] лучше разделить FieldModel и FormFIeldModel на две модели. FieldModel часто используется просто для обычных полей, к которым никакие валидаторы не нужны. и можно будет тогда отнаследовать FormFIeldModel от FieldModel

2024-06-24 08:18 UTC, Margot07008 commented on src/models/FieldModel/FieldModel.ts
> -  private readonly _initialValue: T;
давай сделаешь ValueModel - базовая модель без валидатора и от нее отнаследуешь FieldModel - модель формы с валидатором

initValue я бы оставила в базовой модели

2024-06-25 09:34 UTC, Margot07008 commented on src/models/FormFieldModel/FieldModel.ts
> +import { action, computed, makeObservable, observable } from 'mobx';
файлик тоже бы FormFieldModel назвать

2024-06-25 09:34 UTC, Margot07008 commented on src/models/FormFieldModel/FieldModel.ts
> +    this.setValue(this._initialValue);
здесь нужно сделать `super.reset()`

и убрать отсюда ` this.setValue(this._initialValue); this._resetTouched();`

2024-06-25 09:34 UTC, Margot07008 commented on src/models/FormFieldModel/FieldModel.ts
> +    this._touched = true;
```suggestion
    super.setValue(value);
    this._resetError();
```

2024-06-25 09:34 UTC, Margot07008 commented on src/models/FormFieldModel/FieldModel.ts
> +import { ValueModel } from '../ValueModel';
FormFieldModel не должна копировать методы, которые есть в ValueModel. FormFieldModel по идее расширяет и добавляет только проверку на ошибку. Поэтому, где возможно, лучше делать через super, чтобы не дублировать логику

2025-07-29 13:55 UTC, merged