[+] sentry store
ktsstudio/mediaproject-stores pull request #3
Opened 2022-07-26 12:25 UTC by andrewgul

2022-07-26 13:21 UTC, n-merkulova requested changes

2022-07-26 13:21 UTC, n-merkulova commented on src/stores/BaseRootStore.ts
> +    this.sentryStore = sentryStore;
! давай не будем делат стор сентри в рут сторе, пусть это будет просто экспортируемый класс, который можно будет при желании использовать

2022-07-26 13:21 UTC, n-merkulova commented on src/stores/BaseRootStore.ts
> +    this.sentryStore = sentryStore;
мне это не нравится, потому что так ты отрезаешь возможность использовать сентри каким-то своим образом или не использовать вовсе. в проекте сентри может и не быть вовсе...

кому нужно будет, тот отнаследуется от класса рут стора и сделает там сентри стор

2022-07-26 13:21 UTC, n-merkulova commented on src/stores/SentryStore.ts
> +  SentryVKUserConfigType,
можно наверно без config, это же по сути просто тип юзера

2022-07-26 13:21 UTC, n-merkulova commented on src/stores/SentryStore.ts
> +        type: 'vk_bridge',
мб тут еще метод передавать?

2022-07-26 13:21 UTC, n-merkulova commented on src/stores/types/api.ts
> +      error_type: 'auth_error';
так а почему не сделать просто error_type: 'auth_error' | 'api_error' | 'client_error'?

2022-07-26 13:44 UTC, andrewgul commented on src/stores/types/api.ts
> +      error_type: 'auth_error';
в [доке](https://dev.vk.com/mini-apps/bridge) написано что для разных `error_type` будут разные `error_data`, посчитал что так типизировать будет правильнее

2022-07-27 08:16 UTC, AliceSitedge requested changes

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +      !window.is_dev && Sentry.getCurrentHub().getClient() && this._inited
Обычно тут `is_production` используем и мне кажется это логичнее, чтобы из дева тоже ошибки присылались, для сф тестирований всяких полезно

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +    if (!window.is_dev) {
Тут тоже мб `if (window.is_production)`?

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +      !window.is_dev && Sentry.getCurrentHub().getClient() && this._inited
А может быть такое, что клиент не определен? `this._inited` же устанавливается только после `Sentry.init`

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +  };
Кажется, что можно один метод сделать и принимать `SentryUserConfigType | SentryVKUserConfigType`

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +        data: errorEvent.data,
payload тут не нужно?

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +        data: errorEvent.data,
И можно еще назвать errorData, чтобы точно было понятно, что это за данные

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/SentryStore.ts
> +        type: 'vk_bridge',
Можно еще error_type наверное, раз он точно есть в типе VKBridgeErrorEventType

2022-07-27 08:16 UTC, AliceSitedge commented on src/stores/types/api.ts
> +export type ApiErrorDataType = {
Этот тип потом будет из mediaproject-utils браться, отсюда удалишь?

2022-07-27 08:18 UTC, AliceSitedge commented
Кстати еще changelog нужен и повышение версии

2022-07-29 15:56 UTC, n-merkulova commented on src/stores/SentryStore.ts
> +      !window.is_dev && Sentry.getCurrentHub().getClient() && this._inited
на этот случай тут проверка Sentry.getCurrentHub().getClient()

2022-07-29 15:57 UTC, n-merkulova commented on src/stores/SentryStore.ts
> +      !window.is_dev && Sentry.getCurrentHub().getClient() && this._inited
в принципе согласна, потому что в сентри еще можно фильтровать ошибки дева и прода

2022-07-29 18:04 UTC, merged