Модель списка с пагинацией для api + расширенная модель для мокапов
ktsstudio/mediaproject-stores pull request #5
Opened 2023-03-20 11:23 UTC by wayvy

### ApiListModel<T, RestApiT>

Модель предназначена для работы со списками, которые загружаются с сервера.
Предоставляет методы для загрузки данных с сервера с оффсетом или пагинацией, контроля состояния загрузки, сброса данных.
При достижении конца списка, модель устанавливает флаг, что список загружен.

* T - Тип данных, которые будут храниться в модели.
* RestApiT - Тип данных, которые приходят с сервера, в случае, если нужно вернуть какие-то данные, которые не относятся к списку. Возвращается из методов load/refresh. 

 * @param fetchFunction - Callback-функция для загрузки данных с сервера. При вызове функции, в неё передаётся объект fetchProps: { listLength, listLoaded, limitCountPerRequest, empty, lastItem, lastItemId, currentPage }
 * @param limitPerRequest - Количество элементов, которое нужно загрузить с сервера за один запрос.

 * @method load - Загрузить данные с сервера.
 * @method refresh - Сбросить данные и загрузить заново.
 * @method reset - Сбросить данные.

### MockApiListModel<T, RestApiT>

Модель расширяет ApiListModel, добавляя возможность работы с мокапами.

 * @param sleepMs - Время в миллисекундах, которое нужно подождать перед тем, как вернуть данные.
 * @param listLengthLimit - Максимальная длина всего списка, который будет сгенерирован. Если не указано, то будет генерироваться бесконечный список.

2023-03-21 09:22 UTC, AliceSitedge requested changes

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +      _listLoaded: observable.ref,
Тут наверное ref не нужен, это же просто boolean

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +  private _meta: MetaModel = new MetaModel();
readonly можно сделать

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +  private _fetchFunction: ApiListFetchFunction<T, RestApiT>;
Тоже readonly?

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +    const restApiData = await this.load();
Можно сразу тут return сделать

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +  public get list(): T[] {
Может сначала геттеры объявить, а потом экшены?

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/types.ts
> +  lastItem: unknown;
Может быть `ApiListFetchProps` сделать дженериком и прокидывать в него тип айтема?

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +      lastItemId: this.lastItemId,
Может быть будет достаточно возвращать lastItem? А внутри функции с фетчем из него уже достать нужное поле. Если ApiListFetchProps сделать дженериком, то вполне удобно должно получиться, потому что там будет описан тип айтема. А то логика с поиском поля id немного нагроможденно выглядит

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +      empty: this.empty,
Это тоже можно получить из listLength при необходимости, мне кажется можно не возвращать это тут

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +    return this._list[this.listLength - 1];
Тут не нужно отдельно обработать случай, если список пустой?

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +    return this.listLength / this.limitCountPerRequest;
Наверное нужно привести к целому. Апишка может вернуть меньше элементов, если это например последняя страница

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +    this.meta.setLoadedSuccessMeta();
Как будто логичнее, если это будет внутри load

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/types.ts
> +  : ResponseApiListType<T> & ResponseRestApiType<RestApiT>;
Мне кажется тут можно было бы просто один тип сделать с опциональным полем `restApiData` и опциональным вторым типом в дженерике `RestApiT = undefined`

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +    return restApiData;
Как будто ничего не изменилось в методе

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +  private _sleepMs: number;
readonly?

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +      _sleep: action,
Этот метод не модифицирует поля

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +        this._listLengthLimit &&
_listLengthLimit может быть 0 , если нужно какую-то заглушку потестить например

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +    listLengthLimit: number
А это же можно просто из поля стора достать

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/types.ts
> +  list: T[];
А как обработать случай, если в ответе вернулась ошибка? Просто по типу я могу вернуть только массив из `T`, но если я верну например пустой массив, то ошибка не покажется (не вызовется `this.meta.setLoadedErrorMeta()`). Может здесь сделать тип `T[] | null`?

2023-03-21 09:22 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +      const result = await this._fetchFunction(this);
Может быть передавать сюда только fetchProps? Или это для чего-то может понадобиться?

2023-03-21 09:25 UTC, AliceSitedge requested changes

2023-03-21 09:25 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +    if (apiListResponse.length < this.limitCountPerRequest) {
Еще мне кажется эту логику может понадобиться переопределить. Может сделать метод, который будет просто это высчитывать, но не устанавливать _listLoaded, с возможностью его переопределить?

2023-03-21 17:22 UTC, qpounodb commented on src/models/lists/ApiListModel/ApiListModel.ts
> +    makeObservable<ApiListModel<T, RestApiT>, ApiListModelPrivateFields>(this, {
можно сократить немного, будет удобно в случае переименования класса или его дженерик параметров
```suggestion
    makeObservable<this, ApiListModelPrivateFields>(this, {
```

2023-03-21 17:22 UTC, qpounodb commented on src/models/lists/ApiListModel/ApiListModel.ts
> +      'restApiData' in result ? result.restApiData : undefined;
Кажется можно сразу в `return` перенести, если в самом методе `restApiData` не планируется использовать

2023-03-21 17:22 UTC, qpounodb commented on src/models/lists/ApiListModel/ApiListModel.ts
> +  protected _setFetchResult(result: ResponseApiType<T, RestApiT>) {
```suggestion
  protected _setFetchResult(result: ResponseApiType<T, RestApiT>): RestApiT | undefined {
```

2023-03-21 17:22 UTC, qpounodb commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +    >(this, {
```suggestion
    makeObservable<this, MockApiListModelPrivateFields>(this, {
```

2023-03-21 17:22 UTC, qpounodb commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +class MockApiListModel<T, ApiT = T, RestApiT = undefined> extends ApiListModel<
Похоже параметр `ApiT = T` параметр нигде не используется

2023-04-20 17:03 UTC, AliceSitedge requested changes

2023-04-20 17:03 UTC, AliceSitedge commented on src/models/lists/ApiListModel/ApiListModel.ts
> +      this.meta.setLoadedSuccessMeta();
Тут проблема, что строкой выше вызывается `_setFetchResult`, в котором есть проверка на отсутствие результата, и если результата нет, там вызывается `this.meta.setLoadedErrorMeta()`. А здесь вызывается `this.meta.setLoadedSuccessMeta()`, что перетирает установленную ошибку

Может быть проверку на отсутствие результата переместить в метод `load`? Аналогично модели для мокового списка

2023-04-20 17:03 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +      // refresh: override,
Остался коммент

2023-04-20 17:03 UTC, AliceSitedge commented on src/models/lists/MockApiListModel/MockApiListModel.ts
> +  public override async load(): Promise<RestApiT | undefined> {
Не вижу, чтобы в этом методе где-то вызывался `this.meta.setLoadedSuccessMeta()`. Давай плиз переместим весь контроль над состоянием загрузки в метод `load` и сделаем его единообразным в обеих моделях, чтобы это было проще отслеживать

2023-05-02 06:41 UTC, AliceSitedge approved these changes

2023-07-07 10:55 UTC, merged